# Dependencies
multivews:      true
source:         .
highlighter:    pygments
markdown:       kramdown
# http://jekyllrb.com/docs/permalinks/
permalink:      /:year/:month/:day/:title/

# Setup
title:            Alexander Chamessian
tagline:          
description:      
url:

# Site owner
owner:
  name: Alexander Chamessian
  email: achamess@gmail.com
  vita:
  twitter: achamess
  instagram: "achamess"
  github: "achamess"
  facebook: "alexander.chamessian"
  google:
    analytics: 
    plus: 
  bing:
    verify: 

  bio: "My personal blog"
  avatar: 

paginate:         8

figures:
  dir: /figures
  enumerate: true
  analytics: true

links:
  - title: Home
    url: /
  - title: Colophon
    url: /about/
  - title: Archives
    url: /archives/
  - title: Digital & Public History
    url: /digital/
  - title: Research
    url: /research/
  - title: Teaching
    url: /teaching/

google_analytics_tracking_id: 
