# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Alexander Chamessian
tagline:          MD-PhD Student
description:      
baseurl:          /

author:
  name:           'Alexander Chamessian'
  url:            https://twitter.com/achamess

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
